//get alle admin@htw
GET http://localhost:3000/reisen/61bf62310f732aa4ed0a1641

###
//get alle huene@hwt@htw
GET http://localhost:3000/reisen/61bf62310f732aa4ed0a1643

###
//get eine admin@htw
GET http://localhost:3000/reisen/61bf62310f732aa4ed0a1641/61bf6392b0d72fed0dd7e1bf

###
//get eine huene@hwt@htw
GET http://localhost:3000/reisen/61bf62310f732aa4ed0a1643/61bf6405b0d72fed0dd7e1c3

###
//post eine admin@htw
POST  http://localhost:3000/reisen/61bf62310f732aa4ed0a1641
Content-Type: application/json

{
    "name": "Reise1",
    "date1": "2000-01-01",
    "date2": "2001-01-01",
    "country": "Germany"
}

###
//post eine huene@hwt@htw
POST  http://localhost:3000/reisen/61bf62310f732aa4ed0a1643
Content-Type: application/json

{
    "name": "Reise2",
    "date1": "2002-01-01",
    "date2": "2003-01-01",
    "country": "Austria"
}

###
//delete eine admin@htw
DELETE http://localhost:3000/reisen/61bf62310f732aa4ed0a1641/61bf659eb0d72fed0dd7e1ca

###
//delete eine huene@hwt@htw
DELETE http://localhost:3000/reisen/61bf62310f732aa4ed0a1643/61bf65bbb0d72fed0dd7e1cc

###
//patch eine admin@htw
PATCH http://localhost:3000/reisen/61bf62310f732aa4ed0a1641/61bf659eb0d72fed0dd7e1ca
Content-Type: application/json

{
    "name": "Reise5",
    "date1": "3637-01-01"
}

###
//patch eine huene@htw
PATCH http://localhost:3000/reisen/61bf62310f732aa4ed0a1643/61bf65bbb0d72fed0dd7e1cc
Content-Type: application/json

{
    "name": "Reise7",
    "date2": "6235-01-01"
}

###
POST http://localhost:3000/login
Content-Type: application/json

{
    "email": "huene@htw-berlin.de",
    "password": "hunter2"
}

###
GET http://localhost:3000/uid
